version: "3.8"

services:
  api:
    container_name: shortcut-master-api
    build:
      context: ./shortcut-master-api
      dockerfile: ../Dockerfile.shortcut-master-api
    volumes:
      - ./shortcut-master-api:/app:cached
      - /app/node_modules
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm run start:dev
  db:
    container_name: shortcut-master-db
    build:
      context: ./
      dockerfile: ./Dockerfile.shortcut-master-db
    volumes:
      - ./shortcut-master-db/volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: shortcut-master-db
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - 5000:5000
  web:
    container_name: shortcut-master-web
    build:
      context: ./shortcut-master-web
      dockerfile: ../Dockerfile.shortcut-master-web
    volumes:
      - ./shortcut-master-web:/app:cached
      - /app/node_modules
    tty: true
    ports:
      - 8000:8000
    command: npm run dev
